[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    '@decentral.ee/=node_modules/@decentral.ee/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@superfluid-finance/=node_modules/@superfluid-finance/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config